### PR TITLE
Update badges

### PR DESCRIPTION
**Pull request by MeltySnow**
@nottrobin asked me to update the badges to make them more consistent

## Done

Added CircleCI and code coverage badges to the README

## QA

- Check out this feature branch

### CODE REVIEW

**Comment by tbille** [comment]
We are not using CircleCi of code coverage on this project.
Closing this issue.

Thanks!

**Comment by nottrobin** [comment]
@tbille why aren't we using circleci? Couldn't we start?

**Comment by tbille** [comment]
Don't know why.
Yes I guess we can.

**Comment by nottrobin** [comment]
I was hoping these badges PRs that I asked @MeltySnow to create could be an impetus for us to unify our CI process across projects - moving from Travis to CircleCI where we're still using Travis is one example of this. Another is code-coverage - we should ideally set up code coverage reports for any projects that have any sort of testing.

But there's no specific urgency on any of it, just if anyone gets a sec.

**Pull request closed without merging**
